gpg fixes on msater branch

diff --git a/4.1/Dockerfile.mongodb-userfix b/4.1/Dockerfile.mongodb-userfix
--- a/4.1/Dockerfile.mongodb-userfix
+++ b/4.1/Dockerfile.mongodb-userfix
@@ -25,62 +25,69 @@ RUN addgroup --gid $MONGODB_GRP_ID $MONGODB_GRP
 RUN useradd -r $MONGODB_USER --uid $MONGODB_USER_ID --gid $MONGODB_GRP_ID
 
 RUN set -eux; \
-	apt-get update; \
-	apt-get install -y --no-install-recommends \
-		ca-certificates \
-		jq \
-		numactl \
-	; \
-	if ! command -v ps > /dev/null; then \
-		apt-get install -y --no-install-recommends procps; \
-	fi; \
-	rm -rf /var/lib/apt/lists/*
+  apt-get update; \
+  apt-get install -y --no-install-recommends \
+    ca-certificates \
+    jq \
+    numactl \
+  ; \
+  if ! command -v ps > /dev/null; then \
+    apt-get install -y --no-install-recommends procps; \
+  fi; \
+  rm -rf /var/lib/apt/lists/*
 
 # grab gosu for easy step-down from root (https://github.com/tianon/gosu/releases)
 ENV GOSU_VERSION 1.11
 # grab "js-yaml" for parsing mongod's YAML config files (https://github.com/nodeca/js-yaml/releases)
 ENV JSYAML_VERSION 3.13.0
 
+
+## https://github.com/inversepath/usbarmory-debian-base_image/issues/9
+## Error fix: gpg: keyserver receive failed: Cannot assign requested address
+
+ENV GPGCMD gpg2
+
 RUN set -ex; \
-	\
-	apt-get update; \
-	apt-get install -y --no-install-recommends \
-		wget \
-	; \
-	if ! command -v gpg > /dev/null; then \
-		apt-get install -y --no-install-recommends gnupg dirmngr; \
-	fi; \
-	rm -rf /var/lib/apt/lists/*; \
-	\
-	dpkgArch="$(dpkg --print-architecture | awk -F- '{ print $NF }')"; \
-	wget -O /usr/local/bin/gosu "https://github.com/tianon/gosu/releases/download/$GOSU_VERSION/gosu-$dpkgArch"; \
-	wget -O /usr/local/bin/gosu.asc "https://github.com/tianon/gosu/releases/download/$GOSU_VERSION/gosu-$dpkgArch.asc"; \
-	export GNUPGHOME="$(mktemp -d)"; \
-	gpg --batch --keyserver ha.pool.sks-keyservers.net --recv-keys B42F6819007F00F88E364FD4036A9C25BF357DD4; \
-	gpg --batch --verify /usr/local/bin/gosu.asc /usr/local/bin/gosu; \
-	command -v gpgconf && gpgconf --kill all || :; \
-	rm -r "$GNUPGHOME" /usr/local/bin/gosu.asc; \
-	chmod +x /usr/local/bin/gosu; \
-	gosu --version; \
-	gosu nobody true; \
-	\
-	wget -O /js-yaml.js "https://github.com/nodeca/js-yaml/raw/${JSYAML_VERSION}/dist/js-yaml.js"; \
+  \
+  apt-get update; \
+  apt-get install -y --no-install-recommends \
+    wget \
+  ; \
+  if ! command -v gpg > /dev/null; then \
+    apt-get install -y --no-install-recommends gnupg dirmngr gnupg2; \
+  fi; \
+  rm -rf /var/lib/apt/lists/*; \
+  \
+  dpkgArch="$(dpkg --print-architecture | awk -F- '{ print $NF }')"; \
+  wget -O /usr/local/bin/gosu "https://github.com/tianon/gosu/releases/download/$GOSU_VERSION/gosu-$dpkgArch"; \
+  wget -O /usr/local/bin/gosu.asc "https://github.com/tianon/gosu/releases/download/$GOSU_VERSION/gosu-$dpkgArch.asc"; \
+  export GNUPGHOME="$(mktemp -d)"; \
+  $GPGCMD --batch --keyserver ha.pool.sks-keyservers.net --recv-keys B42F6819007F00F88E364FD4036A9C25BF357DD4; \
+  $GPGCMD --batch --verify /usr/local/bin/gosu.asc /usr/local/bin/gosu; \
+  command -v gpgconf && gpgconf --kill all || :; \
+  rm -r "$GNUPGHOME" /usr/local/bin/gosu.asc; \
+  chmod +x /usr/local/bin/gosu; \
+  gosu --version; \
+  gosu nobody true; \
+  \
+  wget -O /js-yaml.js "https://github.com/nodeca/js-yaml/raw/${JSYAML_VERSION}/dist/js-yaml.js"; \
 # TODO some sort of download verification here
-	\
-	apt-get purge -y --auto-remove wget
+  \
+  apt-get purge -y --auto-remove wget
 
 RUN mkdir /docker-entrypoint-initdb.d
 
+ENV GPGCMD gpg2
 ENV GPG_KEYS E162F504A20CDF15827F718D4B7C549A058F8B6B
 RUN set -ex; \
-	export GNUPGHOME="$(mktemp -d)"; \
-	for key in $GPG_KEYS; do \
-		gpg --batch --keyserver ha.pool.sks-keyservers.net --recv-keys "$key"; \
-	done; \
-	gpg --batch --export $GPG_KEYS > /etc/apt/trusted.gpg.d/mongodb.gpg; \
-	command -v gpgconf && gpgconf --kill all || :; \
-	rm -r "$GNUPGHOME"; \
-	apt-key list
+  export GNUPGHOME="$(mktemp -d)"; \
+  for key in $GPG_KEYS; do \
+    $GPGCMD --batch --keyserver ha.pool.sks-keyservers.net --recv-keys "$key"; \
+  done; \
+  $GPGCMD --batch --export $GPG_KEYS > /etc/apt/trusted.gpg.d/mongodb.gpg; \
+  command -v gpgconf && gpgconf --kill all || :; \
+  rm -r "$GNUPGHOME"; \
+  apt-key list
 
 # Allow build-time overrides (eg. to build image with MongoDB Enterprise version)
 # Options for MONGO_PACKAGE: mongodb-org OR mongodb-enterprise
@@ -96,19 +103,19 @@ ENV MONGO_VERSION 4.1.13
 RUN echo "deb http://$MONGO_REPO/apt/ubuntu bionic/${MONGO_PACKAGE%-unstable}/$MONGO_MAJOR multiverse" | tee "/etc/apt/sources.list.d/${MONGO_PACKAGE%-unstable}.list"
 
 RUN set -x \
-	&& apt-get update \
-	&& apt-get install -y \
-		${MONGO_PACKAGE}=$MONGO_VERSION \
-		${MONGO_PACKAGE}-server=$MONGO_VERSION \
-		${MONGO_PACKAGE}-shell=$MONGO_VERSION \
-		${MONGO_PACKAGE}-mongos=$MONGO_VERSION \
-		${MONGO_PACKAGE}-tools=$MONGO_VERSION \
-	&& rm -rf /var/lib/apt/lists/* \
-	&& rm -rf /var/lib/mongodb \
-	&& mv /etc/mongod.conf /etc/mongod.conf.orig
+  && apt-get update \
+  && apt-get install -y \
+    ${MONGO_PACKAGE}=$MONGO_VERSION \
+    ${MONGO_PACKAGE}-server=$MONGO_VERSION \
+    ${MONGO_PACKAGE}-shell=$MONGO_VERSION \
+    ${MONGO_PACKAGE}-mongos=$MONGO_VERSION \
+    ${MONGO_PACKAGE}-tools=$MONGO_VERSION \
+  && rm -rf /var/lib/apt/lists/* \
+  && rm -rf /var/lib/mongodb \
+  && mv /etc/mongod.conf /etc/mongod.conf.orig
 
 RUN mkdir -p /data/db /data/configdb \
-	&& chown -R mongodb:mongodb /data/db /data/configdb
+  && chown -R mongodb:mongodb /data/db /data/configdb
 VOLUME /data/db /data/configdb
 
 COPY docker-entrypoint.sh /usr/local/bin/
